#include "main.h"

#include <stdio.h>
#include <stdlib.h>

/* TODO: */

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:

// screen images
#include "images/start_screen.h"
#include "images/snow_scene.h"
#include "images/win_screen.h"
#include "images/lose_screen.h"



/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

struct penguin player;
struct penguin *playerP = &player;
struct puffle puffles[9];


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
 

  setup();

  // initialize score
  int score = 0;

  //initialize timer to 20 seconds
  int timer = 60 * 20;


  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // reset game
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      setup();

      score = 0;
      timer = 60 * 20;

      state = START;
    }

    if (score == 9) {
      state = WIN;
    }

    //if timer just ran out of time
    if (timer <= 0 && timer > -200) {
      state = LOSE;
    }

    waitForVBlank();
    timer--;

    switch (state) {

      case START:
        drawFullScreenImageDMA(start_screen);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(snow_scene);
          state = PLAY;
        }
        break;


      case PLAY:
        // draw penguin
        drawImageDMA(playerP -> row, playerP -> col, playerP -> width, playerP -> height, playerP -> image);

        // undraw old puffles
        for (int i = 0; i < 9; i++) {
          if (puffles[i].show) {
            undrawImageDMA(puffles[i].row, puffles[i].col, puffles[i].row + puffles[i].height, puffles[i].col + puffles[i].width, snow_scene);
          }
        }
          
        // draw new puffles
        for (int i = 0; i < 9; i++) {

          if (!puffles[i].show) continue;

          // check for collision
          if (abs(puffles[i].row - (playerP -> row)) < 30 && abs(puffles[i].col - (playerP -> col)) < 25) {
            puffles[i].show = 0;
            score++;

            // undraw old score
            undrawImageDMA(150, 185, 160, 240, snow_scene);

            continue;
          }

          if (puffles[i].row + puffles[i].vertDis < 0 || puffles[i].row + puffles[i].vertDis > HEIGHT - puffles[i].height) {
            puffles[i].vertDis = -puffles[i].vertDis;
          }
          if (puffles[i].col + puffles[i].horDis < 0 || puffles[i].col + puffles[i].horDis > WIDTH - puffles[i].width) {
            puffles[i].horDis = -puffles[i].horDis;
          }
          puffles[i].row += puffles[i].vertDis;
          puffles[i].col += puffles[i].horDis;
          drawImageDMA(puffles[i].row, puffles[i].col, puffles[i].width, puffles[i].height, puffles[i].image);

        }

        control(currentButtons, previousButtons);

        // draw score
        char buffer[51];
        sprintf(buffer, "Score: %d", score);
        drawString(150, 185, buffer, BLUE);

        // undraw old timer
        undrawImageDMA(130, 185, 140, 240, snow_scene);

        // draw timer
        char timeBuffer[51];
        sprintf(timeBuffer, "Time Left: %d", timer / 60);
        drawString(130, 155, timeBuffer, RED);

        break;


      case WIN:
        timer = -200;
        drawFullScreenImageDMA(win_screen);
        break;


      case LOSE:
        drawFullScreenImageDMA(lose_screen);
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
