#include "main.h"

#include <stdio.h>
#include <stdlib.h>

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:

#include "images/start_screen.h"
#include "images/snow_scene.h"

#include "images/blue_puffle.h"
#include "images/pink_puffle.h"
#include "images/green_puffle.h"
#include "images/brown_puffle.h"
#include "images/yellow_puffle.h"
#include "images/gray_puffle.h"
#include "images/purple_puffle.h"
#include "images/white_puffle.h"
#include "images/red_puffle.h"



/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
 

  // //my own code
  const short unsigned int *images[9] = {blue_puffle, pink_puffle, yellow_puffle, green_puffle, white_puffle, red_puffle, gray_puffle, brown_puffle, purple_puffle};
  struct puffle puffles[9];
  for (int i = 0; i < 9; i++) {
    puffles[i].row = (i * BLUE_PUFFLE_HEIGHT) % HEIGHT;
    puffles[i].col = (i * BLUE_PUFFLE_WIDTH) % WIDTH;
    puffles[i].height = BLUE_PUFFLE_HEIGHT;
    puffles[i].width = BLUE_PUFFLE_WIDTH;
    puffles[i].image = images[i];
  }


  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    waitForVBlank();

    switch (state) {
      case START:
        drawFullScreenImageDMA(start_screen);

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
        }

        // state = ?
        break;
      case PLAY:

        drawFullScreenImageDMA(snow_scene);
        for (int i = 0; i < 9; i++) {
          drawImageDMA(puffles[i].row, puffles[i].col, puffles[i].width, puffles[i].height, puffles[i].image);
        }
        

        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          for (int i = 0; i < 9; i++) {
            if (puffles[i].row >= 5) {
              int maxMove = 5;
              for (int x = 0; x < 9; x++) {
                int distance = puffles[i].row - puffles[x].row;
                if (distance > 0 && distance < maxMove + puffles[i].height) {
                  maxMove = distance;
                }
              }
              puffles[i].row -= maxMove;
              
            }
          }
          
        }
        if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          for (int i = 0; i < 9; i++) {
            if (puffles[i].row <= HEIGHT - 5 - puffles[i].height) {
              puffles[i].row += 5;
            }
          }
          
        }
        if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          for (int i = 0; i < 9; i++) {
            if (puffles[i].col >= 5) {
              puffles[i].col -= 5;
            }
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          for (int i = 0; i < 9; i++) {
            if (puffles[i].col <= WIDTH - 5 - puffles[i].width) {
              puffles[i].col -= 5;
            }
          }
        }

			break;

        // state = ?
        break;
      case WIN:

        // state = ?
        break;
      case LOSE:

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
